# Permalinks
permalink:        pretty
exclude:          [themes]
# Setup
title:            Mandrake
tagline:          'A recipe book'
description:      'Decide what to cook for any meal of the day'
url:              http://hyde.getpoole.com
baseurl:          '/'

author:
  name:           'Robert Irwin'
  url:            https://twitter.com/irwinian

paginate:         5

# Custom vars
version:          2.1.0
