# Permalinks
permalink:        pretty
exclude:          [themes]
# Setup
title:            Recipe book
tagline:          'A recipe book'
description:      'A book of simple recipes'
url:              https://rowinf.github.io/recipebook/
baseurl:          /recipebook/

author:
  name:           'Robert Irwin'
  url:            https://twitter.com/irwinian

paginate:         5

# Custom vars
version:          2.1.0
