# Permalinks
permalink:        pretty
exclude:          [themes, spec, modules]
# Setup
title:            Recipe book
tagline:          'A recipe book'
description:      'Decide what to cook for any meal of the day'
url:              http://hyde.getpoole.com
baseurl:          https://rowinf.github.io/recipebook/

author:
  name:           'Robert Irwin'
  url:            https://twitter.com/irwinian

paginate:         5

# Custom vars
version:          2.1.0
