# Permalinks
permalink:        pretty
exclude:          [themes]
# Setup
title:            Recipe book
tagline:          'A recipe book'
description:      'A book of simple recipes'
url:              https://rowinf.github.io
baseurl:          /recipebook/
theme:            minima

author:           'Robert Irwin'
github_username:  rowinf

paginate:         5

# Custom vars
version:          2.1.0
